### PR TITLE
Added python tester Files into workflow

### PR DESCRIPTION
**Pull request by maxs-rose**
Add the python tester files into the workflow.

### CODE REVIEW

**Comment by CThuleHansen** [comment]
Looking pretty good. Would it make sense to create a single python file encompassing the other three?

**Comment by maxs-rose** [comment]
@CThuleHansen if you are meaning create a new python file that will run all 3 tests and call that from the workflow that would definitely make the workflow cleaner.

However each tests would not be itemised in the details and you would have to look at the console output so it really depends on how you want it to behave

**Comment by CThuleHansen** [comment]
> @CThuleHansen if you are meaning create a new python file that will run all 3 tests and call that from the workflow that would definitely make the workflow cleaner.

This should be the case. Otherwise it will not be run locally either. It is too cumbersome. Same with automatically extracting the path, so it does not have to be an argument. It completely ruins the flow.

> 
> However each tests would not be itemised in the details and you would have to look at the console output so it really depends on how you want it to behave

So let it be That is the reason for the many ######### :)

**Comment by maxs-rose** [comment]
I will make the path parameter optional and have it default to the  expected output location so that it can still be used from anywhere. 

That will clean up the workflow nicely.

I will also add a new script that runs both of the tests but leave the workflow running them individually just so it get nicely itemized.

**Comment by CThuleHansen** [comment]
Sounds good!

**Comment by maxs-rose** [comment]
That is now all done.
To make it a bit more flexible each script now takes the name of the jar file as a separate parameter.

Also, the checks on this pull fail due to the issue with the web api being run on windows so they are expected :)

**Comment by CThuleHansen** [comment]
I am wondering a bit about the macos-latest failure?

**Comment by maxs-rose** [comment]
Yea I am  not sure about that since it passes on the fork I made 🤔

Will have a look into it

**Comment by maxs-rose** [comment]
made it run again and it now works...

Possibly the failure was something on githubs end since the output also seems a little jumbled in the one that failed

**Comment by CThuleHansen** [comment]
Could you merge development in again and see if it fixed windows-latest?

**Comment by maxs-rose** [comment]
Other than #182 there is currently nothing for me to pull in

**Comment by CThuleHansen** [comment]
I have just merged to development. 
Could you try and debug around here:
https://github.com/INTO-CPS-Association/maestro/blob/development/frameworks/fmi2/src/main/java/org/intocps/maestro/framework/fmi2/Fmi2FmuValidator.java#L56?

I have a suspecion that it is either file seperators, the semicolon that should be a colon or something.
The test `DocumentationGettingStartedExamplesTest` runs the validator.

I have a windows laptop, but it is at the closed uni currently...

**Comment by maxs-rose** [comment]
Any combination of semicolon and colon pass the test in windows but all result in the same "Specification did not verify" when compiled into the webapi.

It has also caused the CLI version to start failing when compiled with:
```console
Exception in thread "main" java.lang.NoClassDefFoundError: org/intocps/maestro/framework/fmi2/api/Fmi2Builder$Variable
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3296)
        at java.base/java.lang.Class.getConstructor0(Class.java:3501)
        at java.base/java.lang.Class.newInstance(Class.java:626)
        at org.intocps.maestro.plugin.PluginFactory.lambda$getPlugins$1(PluginFactory.java:48)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.intocps.maestro.plugin.PluginFactory.getPlugins(PluginFactory.java:53)
        at org.intocps.maestro.MablSpecificationGenerator.loadExpansionPlugins(MablSpecificationGenerator.java:60)
        at org.intocps.maestro.MablSpecificationGenerator.generateFromDocuments(MablSpecificationGenerator.java:354)
        at org.intocps.maestro.Mabl.expand(Mabl.java:255)
        at org.intocps.maestro.Main.argumentHandler(Main.java:175)
        at org.intocps.maestro.Main.main(Main.java:232)
Caused by: java.lang.ClassNotFoundException: org.intocps.maestro.framework.fmi2.api.Fmi2Builder$Variable
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 19 more
```

**Comment by CThuleHansen** [comment]
That was a new mistake.. will check it out when I have time...

**Comment by CThuleHansen** [comment]
Hmm I am not experiencing those. Did you rebuild before you ran? something like `mvn clean package -DskipTests -Dmaven.javadoc.skip=true"`

**Comment by maxs-rose** [comment]
yea I cleaned and packaged before I ran scripts so not sure what is going on there

**Comment by maxs-rose** [comment]
Is it possible that the mvn build is the problem because when I run the web api from intelij the specification verifies? (running before the changes from #182)

**Pull request merged**
