### PR TITLE
Fixed various issues

### PR DESCRIPTION
**Pull request by CThuleHansen**
- Temporary fix for inputs not being set in initializer plugin (@SimplisticCode, @maxs-rose)
- Created tests for GATestController (@maxs-rose )
- Added directory FMU by using different FMU loader in interpreter.

### CODE REVIEW

**Comment by maxs-rose** [comment]
I would expect outputs.csv to be [outputs.txt](https://github.com/INTO-CPS-Association/maestro/files/5931185/outputs.txt) (obviously as a csv but GitHub won't let me attach one of those) but you seem to be testing against 
[outputs.txt](https://github.com/INTO-CPS-Association/maestro/files/5931189/outputs.txt)

**Comment by CThuleHansen** [comment]
> I would expect outputs.csv to be [outputs.txt](https://github.com/INTO-CPS-Association/maestro/files/5931185/outputs.txt) (obviously as a csv but GitHub won't let me attach one of those) but you seem to be testing against
> [outputs.txt](https://github.com/INTO-CPS-Association/maestro/files/5931189/outputs.txt)

Sorry where do I. do this?

**Comment by maxs-rose** [comment]
[maestro-webapi/src/test/resources/maestro2/188/outputs.csv](maestro-webapi/src/test/resources/maestro2/188/outputs.csv) is just the first timestep unless I am misunderstanding and you not checking against the content of this file

**Comment by CThuleHansen** [comment]
> [maestro-webapi/src/test/resources/maestro2/188/outputs.csv](https://github.com/INTO-CPS-Association/maestro/blob/a4effadcefc2eaa3cb889948b429054c971c49c7/maestro-webapi/src/test/resources/maestro2/188/outputs.csv) is just the first timestep unless I am misunderstanding and you not checking against the content of this file

The last bit :D

**Pull request merged**
