### PR TITLE
  Restructures docs and updates project readme

### PR DESCRIPTION
**Pull request by prasadtalasila**
* Updates project readme to include development steps.
* Updates the sphinx doc generation. All the plugin documentation has been consolidated to docs/plugins directory.

This PR solves the #61 in a different way. While the #61 asks for auto-generation of documentation from the names of directories in *maestro/plugins*, such a suggestion is in contrast with the existing `docs/` setup. In the existing `docs/` setup, all the documentation has been consolidated to one place. Spreading out the documentation of plugins to the code directories violates this convention.
Instead all the plugin documentation is consolidated to `docs/plugins`.

To document a new plugin, we only need to place *<plugin_name>.rst* in the `docs/plugins`; sphinx doc generation will automatically include the new rst document.

### CODE REVIEW

**Comment by CThuleHansen** [comment]
So this is both good and bad. I like your argumentation, yet it couples the development of plugins stronger to the development of maestro.  

It also requires the developer to understand sphinx and rst instead of markdown.
(Is it possible to write in markdown instead of rst?)
Also, it will not display the plugin readme when navigating on i.e. github or when having cloned the repository.

With these things in mind, I think having a local readme.md within each plugin is a better approach.

I look forward to your input!

**Comment by clegaard** [comment]
> It also requires the developer to understand sphinx and rst instead of markdown.
> (Is it possible to write in markdown instead of rst?)

If the docs is generated using sphinx then an extension exists for this:
https://recommonmark.readthedocs.io/en/latest/

In general the benefits of using rst comes if you are doing more advanced stuff, like creating api references.

**Comment by prasadtalasila** [comment]
> So this is both good and bad. I like your argumentation, yet it couples the development of plugins stronger to the development of maestro.
>
> Also, it will not display the plugin readme when navigating on i.e. github or when having cloned the repository.
> 
> With these things in mind, I think having a local readme.md within each plugin is a better approach.
> 
> I look forward to your input!


The basic assumption in the explanation you provide is that the documentation of a plugin should be in the plugin itself. This is another way of saying that the documentation of code should be closer to code itself. But you are suggesting this practice only for plugins but not the other parts of Maestro codebase. 
Infact as the codebase grows, we might have to include the documentation for `ast, core, docs, interpreter, maestro, parser, plugins, typechecker, webapi`. Where do we put this documentation? Is it in their own directories or inside `docs/`?
At the moment, plugins are in the Maestro codebase. It makes enormous sense to put documentation of one codebase at one place. As long as we are keeping the plugins with the rest of the Maestro codebase, it's probably a good idea to consolidate the documentation of plugins into `docs/plugins` directory. 
If there is a real merit in pushing the plugin docs to their own directory and linking it with rst in docs/, that's doable as well.

> 
> It also requires the developer to understand sphinx and rst instead of markdown.
> (Is it possible to write in markdown instead of rst?)

It's certainly possible to write the documentation in markdown using [recommonmark](https://github.com/readthedocs/recommonmark) plugin of Sphinx. We already have this plugin in [our sphinx config](https://github.com/INTO-CPS-Association/maestro/blob/2.0.0-alpha/docs/conf.py#L34).
The **rst** format is not such a stepup from **markdown** format, but is much richer. Here is a really [good comparison](https://news.ycombinator.com/item?id=13724592). In general, the choice of using rst / markdown for the documentation of a java project is a flaky one. The native **javadoc** is really good and tightly integrates with the code. We can include everything including design documents in the javadoc.
As for the use of readme.md files, we first have to make a choice about the true purpose of these files. I see the following choices.
1. We can use *readme.md* to document all information, i.e. installation, developer setup, design, code and user docs. But, this is a really poor choice vis-a-vis javadoc, or even rst.
2. We can use *readme.md* to document *installation* and *developer setup* and migrate rest of the documentation to javadoc.
3. We can use wiki to document  *installation*, *developer setup*, *design*, and *user guide*. Migrate the *code* to javadoc. Using wiki and javadoc allows us to create release-specific documentation. [JUnit5](https://github.com/junit-team/junit5) provides a really good example of this practice. 

JUnit5 team uses [asciidoc](https://asciidoctor.org/). But doing documentation in *wiki*, *javadoc* and *asciidoctor* is too much of an ask for our case. We can get the job done with just *wiki* and *javadoc*.

All-in-all, I would suggest the third choice. I am not rigid about any specific choice. This is a team project. So, perhaps all the team can choose.

PS: If any one of you haven't written javadoc before, it's easy to learn.

**Comment by CThuleHansen** [comment]
Thank you for the thorough explanation, really great input and very informing!

> But you are suggesting this practice only for plugins but not the other parts of Maestro codebase. 

Originally, the plan was that the people creating plugins are not the same people as the ones doing the rest. However, that is probably a naive expectation. Nonetheless, this is the reason for the practice that you mention.

**Regarding your three options:**
Is wiki = Read the docs or github wiki? If RTD, then skip the following paragraph :)
So as I understand it, you are actually in favor of skipping RTD in general use the wiki for more general documentation and javadoc for code-specific documentation? 
We have a long-term plan of switching all of INTO-CPS documentation to RTD and give it a uniform look.

I agree with you in the view on javadoc, we should definitely adopt this! We are just not there yet.
However, I do not see javadoc as particularly good for presenting overviews, where I find diagrams and a more free form of writing superior.

So I think that we should go with option 3, with a readme that introduces the very basic.

**Pull request merged**
