### PR TITLE
Fpm/268 add scenario verifier to the CLI

### LINKED ISSUE #268: Integrate the scenario verifier with the Maestro CLI.
As of now the scenario verifier is only accessible through the web API but should of course also be available through the CLI.

### PR DESCRIPTION
**Pull request by FrederikPM**
Integrated the scenario verifier with the CLI as I understand the CLI and how it is used, so do look into if it is correct.
The logic is tested through tests in external_tester.
Closes #268

### CODE REVIEW

**Comment by lausdahl** [comment]
Please name the branch/pull request with a mening full name instead of just a number. Its hard to get an overview of what this is about. A description would also be nice but not necessary in all cases.

**Review by lausdahl — CHANGES_REQUESTED** [review]
It seems like the scenario verifier isnt a verifier so we need to determine what it is and what its name should be before adding it.

Note: It cannot be called verifier unless it can verify a mabl spec without any other means than the spec. We already use this term for that. I think it is some sort of model based generator that attempts to do correct by construction but I'm not sure.

Also it seems like all the new commands are actually sub commands to this new thing so they should be added like that.

so we have the root like
- export
- import
- "what ever this feature should be called"
  - execute
  - generate
  - verify

looking at this is also seems like some of these could be merged or execute could be extending verify...

**Comment by CThuleHansen** [comment]
Naming ideas are welcome!

**Comment by FrederikPM** [comment]
For now this feature is just called scenario-verifier after the underlying tool and the actual commands have now been made as subcommands.
Should it be merged like this or should I wait until a better name for the feature exists?

**Comment by CThuleHansen** [comment]
Merge merge merge merge!

**Comment by CThuleHansen** [comment]
See #323

**Pull request merged**
